services:
  - type: web
    name: icmp
    env: node
    buildCommand: cd front-end && npm install --legacy-peer-deps && npm run build
    startCommand: cd front-end && npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_KEY
        value: 2f3df4e4-71d6-4f3c-9f02-e6101287e8d8
    autoDeploy: true 