services:
  - type: web
    name: icmp
    env: node
    buildCommand: |
      cd front-end && 
      npm cache clean --force &&
      rm -rf node_modules package-lock.json &&
      npm install &&
      npm run build
    startCommand: cd front-end && npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_KEY
        value: 2f3df4e4-71d6-4f3c-9f02-e6101287e8d8
      - key: REACT_APP_API_URL
        value: https://icmp-api.onrender.com
    autoDeploy: true

  - type: web
    name: icmp-api
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/init_db.py
    startCommand: cd backend && gunicorn application:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ICMP_API_KEY
        sync: false
      - key: FB_VERIFY_TOKEN
        sync: false
      - key: FB_PAGE_ACCESS_TOKEN
        sync: false
      - key: CORS_ORIGINS
        value: https://icmp.onrender.com,https://icmp-events-frontend.onrender.com,https://icmp-events-api.onrender.com,https://icmp-api.onrender.com,https://*.onrender.com

  - type: web
    name: asksameer-website
    env: static
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./website
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - asksameer.com 