services:
  - type: web
    name: icmp
    env: node
    buildCommand: |
      cd front-end && 
      npm cache clean --force &&
      rm -rf node_modules package-lock.json &&
      npm install &&
      npm run build
    startCommand: cd front-end && npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_KEY
        value: 2f3df4e4-71d6-4f3c-9f02-e6101287e8d8
    autoDeploy: true

  - type: web
    name: icmp-api
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/init_db.py
    startCommand: cd backend && gunicorn application:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ICMP_API_KEY
        sync: false 